import { Item } from '../item';
import { PrimeItem } from '../../enums/primeItem';

export const primeItems = {
  missileLauncher: new Item(PrimeItem.MISSILE_LAUNCHER, 0),
  missileExpansion: new Item(PrimeItem.MISSILE_EXPANSION, 0),
  energyTank: new Item(PrimeItem.ENERGY_TANK, 1),
  thermalVisor: new Item(PrimeItem.THERMAL_VISOR, 2),
  xrayVisor: new Item(PrimeItem.XRAY_VISOR, 3),
  variaSuit: new Item(PrimeItem.VARIA_SUIT, 4),
  gravitySuit: new Item(PrimeItem.GRAVITY_SUIT, 5),
  phazonSuit: new Item(PrimeItem.PHAZON_SUIT, 6),
  morphBall: new Item(PrimeItem.MORPH_BALL, 7),
  boostBall: new Item(PrimeItem.BOOST_BALL, 8),
  spiderBall: new Item(PrimeItem.SPIDER_BALL, 9),
  morphBallBomb: new Item(PrimeItem.MORPH_BALL_BOMB, 10),
  powerBombExpansion: new Item(PrimeItem.POWER_BOMB_EXPANSION, 11),
  powerBomb: new Item(PrimeItem.POWER_BOMB, 12),
  chargeBeam: new Item(PrimeItem.CHARGE_BEAM, 13),
  spaceJumpBoots: new Item(PrimeItem.SPACE_JUMP_BOOTS, 14),
  grappleBeam: new Item(PrimeItem.GRAPPLE_BEAM, 15),
  superMissile: new Item(PrimeItem.SUPER_MISSILE, 16),
  wavebuster: new Item(PrimeItem.WAVEBUSTER, 17),
  iceSpreader: new Item(PrimeItem.ICE_SPREADER, 18),
  flamethrower: new Item(PrimeItem.FLAMETHROWER, 19),
  waveBeam: new Item(PrimeItem.WAVE_BEAM, 20),
  iceBeam: new Item(PrimeItem.ICE_BEAM, 21),
  plasmaBeam: new Item(PrimeItem.PLASMA_BEAM, 22),
  artifactOfLifegiver: new Item(PrimeItem.ARTIFACT_OF_LIFEGIVER, 23),
  artifactOfWild: new Item(PrimeItem.ARTIFACT_OF_WILD, 24),
  artifactOfWorld: new Item(PrimeItem.ARTIFACT_OF_WORLD, 25),
  artifactOfSun: new Item(PrimeItem.ARTIFACT_OF_SUN, 26),
  artifactOfElder: new Item(PrimeItem.ARTIFACT_OF_ELDER, 27),
  artifactOfSpirit: new Item(PrimeItem.ARTIFACT_OF_SPIRIT, 28),
  artifactOfTruth: new Item(PrimeItem.ARTIFACT_OF_TRUTH, 29),
  artifactOfChozo: new Item(PrimeItem.ARTIFACT_OF_CHOZO, 30),
  artifactOfWarrior: new Item(PrimeItem.ARTIFACT_OF_WARRIOR, 31),
  artifactOfNewborn: new Item(PrimeItem.ARTIFACT_OF_NEWBORN, 32),
  artifactOfNature: new Item(PrimeItem.ARTIFACT_OF_NATURE, 33),
  artifactOfStrength: new Item(PrimeItem.ARTIFACT_OF_STRENGTH, 34)
};
