import { PrimeWorld } from './world';
import { GeneratedSeed } from '../../../common/models/generatedSeed';

interface PrimeGeneratedSeedArgs {
  id?: string;
  seed?: string;
  settingsString?: string;
  seedHash?: string[];
  createdDate?: Date;
  world?: PrimeWorld;
}

/**
 * Represents a randomized seed (or game) generated by the application.
 */
export class PrimeGeneratedSeed implements GeneratedSeed {
  id: string;
  seed: string;
  settingsString: string;
  seedHash: string[];
  createdDate: Date;
  private world: PrimeWorld;
  private filteredKeys = [
    'id',
    'seed',
    'settingsString',
    'seedHash',
    'createdDate'
  ];

  constructor(args: PrimeGeneratedSeedArgs) {
    Object.assign(this, args);
  }

  getWorld(): PrimeWorld {
    return this.world;
  }

  setWorld(world: PrimeWorld): void {
    this.world = world;
  }

  toClientJson(): string {
    return JSON.stringify(this, this.filteredKeys);
  }

  toClientObject(): GeneratedSeed {
    return {
      id: this.id,
      seed: this.seed,
      settingsString: this.settingsString,
      seedHash: this.seedHash,
      createdDate: this.createdDate
    };
  }

  static fromClientJson(json: string): PrimeGeneratedSeed {
    return new PrimeGeneratedSeed(JSON.parse(json) as PrimeGeneratedSeedArgs);
  }

  static fromClientObject(clientObj: PrimeGeneratedSeedArgs): PrimeGeneratedSeed {
    return new PrimeGeneratedSeed(clientObj);
  }
}
