import { PrimeLocation } from '../../enums/primeLocation';

interface LocationObject {
  name: PrimeLocation
  region: string;
}

/**
 * The array of Metroid Prime locations, sorted in the order the randomprime patcher uses
 */
export const primeLocations: LocationObject[] = [
  // Chozo
  { name: PrimeLocation.MAIN_PLAZA_HALF_PIPE, region: 'Chozo Ruins' },
  { name: PrimeLocation.MAIN_PLAZA_GRAPPLE_LEDGE, region: 'Chozo Ruins' },
  { name: PrimeLocation.MAIN_PLAZA_TREE, region: 'Chozo Ruins' },
  { name: PrimeLocation.MAIN_PLAZA_LOCKED_DOOR, region: 'Chozo Ruins' },
  { name: PrimeLocation.RUINED_FOUNTAIN, region: 'Chozo Ruins' },
  { name: PrimeLocation.RUINED_SHRINE_BEETLE_BATTLE, region: 'Chozo Ruins' },
  { name: PrimeLocation.RUINED_SHRINE_HALF_PIPE, region: 'Chozo Ruins' },
  { name: PrimeLocation.RUINED_SHRINE_LOWER_TUNNEL, region: 'Chozo Ruins' },
  { name: PrimeLocation.VAULT, region: 'Chozo Ruins' },
  { name: PrimeLocation.TRAINING_CHAMBER, region: 'Chozo Ruins' },
  { name: PrimeLocation.RUINED_NURSERY, region: 'Chozo Ruins' },
  { name: PrimeLocation.TRAINING_CHAMBER_ACCESS, region: 'Chozo Ruins' },
  { name: PrimeLocation.MAGMA_POOL, region: 'Chozo Ruins' },
  { name: PrimeLocation.TOWER_OF_LIGHT, region: 'Chozo Ruins' },
  { name: PrimeLocation.TOWER_CHAMBER, region: 'Chozo Ruins' },
  { name: PrimeLocation.RUINED_GALLERY_MISSILE_WALL, region: 'Chozo Ruins' },
  { name: PrimeLocation.RUINED_GALLERY_TUNNEL, region: 'Chozo Ruins' },
  { name: PrimeLocation.TRANSPORT_ACCESS_NORTH, region: 'Chozo Ruins' },
  { name: PrimeLocation.GATHERING_HALL, region: 'Chozo Ruins' },
  { name: PrimeLocation.HIVE_TOTEM, region: 'Chozo Ruins' },
  { name: PrimeLocation.SUNCHAMBER_FLAAHGRA, region: 'Chozo Ruins' },
  { name: PrimeLocation.SUNCHAMBER_GHOSTS, region: 'Chozo Ruins' },
  { name: PrimeLocation.WATERY_HALL_ACCESS, region: 'Chozo Ruins' },
  { name: PrimeLocation.WATERY_HALL_SCAN_PUZZLE, region: 'Chozo Ruins' },
  { name: PrimeLocation.WATERY_HALL_UNDERWATER, region: 'Chozo Ruins' },
  { name: PrimeLocation.DYNAMO_LOWER, region: 'Chozo Ruins' },
  { name: PrimeLocation.DYNAMO_SPIDER_TRACK, region: 'Chozo Ruins' },
  { name: PrimeLocation.BURN_DOME_TUNNEL, region: 'Chozo Ruins' },
  { name: PrimeLocation.BURN_DOME_I_DRONE, region: 'Chozo Ruins' },
  { name: PrimeLocation.FURNACE_SPIDER_TRACKS, region: 'Chozo Ruins' },
  { name: PrimeLocation.FURNACE_TUNNEL, region: 'Chozo Ruins' },
  { name: PrimeLocation.HALL_OF_THE_ELDERS, region: 'Chozo Ruins' },
  { name: PrimeLocation.CROSSWAY, region: 'Chozo Ruins' },
  { name: PrimeLocation.ELDER_CHAMBER, region: 'Chozo Ruins' },
  { name: PrimeLocation.ANTECHAMBER, region: 'Chozo Ruins' },
  // Phendrana
  { name: PrimeLocation.PHENDRANA_SHORELINES_BEHIND_ICE, region: 'Phendrana Drifts' },
  { name: PrimeLocation.PHENDRANA_SHORELINES_SPIDER_TRACK, region: 'Phendrana Drifts' },
  { name: PrimeLocation.CHOZO_ICE_TEMPLE, region: 'Phendrana Drifts' },
  { name: PrimeLocation.ICE_RUINS_WEST, region: 'Phendrana Drifts' },
  { name: PrimeLocation.ICE_RUINS_EAST_BEHIND_ICE, region: 'Phendrana Drifts' },
  { name: PrimeLocation.ICE_RUINS_EAST_SPIDER_TRACK, region: 'Phendrana Drifts' },
  { name: PrimeLocation.CHAPEL_OF_THE_ELDERS, region: 'Phendrana Drifts' },
  { name: PrimeLocation.RUINED_COURTYARD, region: 'Phendrana Drifts' },
  { name: PrimeLocation.PHENDRANA_CANYON, region: 'Phendrana Drifts' },
  { name: PrimeLocation.QUARANTINE_CAVE, region: 'Phendrana Drifts' },
  { name: PrimeLocation.RESEARCH_LAB_HYDRA, region: 'Phendrana Drifts' },
  { name: PrimeLocation.QUARANTINE_MONITOR, region: 'Phendrana Drifts' },
  { name: PrimeLocation.OBSERVATORY, region: 'Phendrana Drifts' },
  { name: PrimeLocation.TRANSPORT_ACCESS, region: 'Phendrana Drifts' },
  { name: PrimeLocation.CONTROL_TOWER, region: 'Phendrana Drifts' },
  { name: PrimeLocation.RESEARCH_CORE, region: 'Phendrana Drifts' },
  { name: PrimeLocation.FROST_CAVE, region: 'Phendrana Drifts' },
  { name: PrimeLocation.RESEARCH_LAB_AETHER_TANK, region: 'Phendrana Drifts' },
  { name: PrimeLocation.RESEARCH_LAB_AETHER_MORPH_TRACK, region: 'Phendrana Drifts' },
  { name: PrimeLocation.GRAVITY_CHAMBER_UNDERWATER, region: 'Phendrana Drifts' },
  { name: PrimeLocation.GRAVITY_CHAMBER_GRAPPLE_LEDGE, region: 'Phendrana Drifts' },
  { name: PrimeLocation.STORAGE_CAVE, region: 'Phendrana Drifts' },
  { name: PrimeLocation.SECURITY_CAVE, region: 'Phendrana Drifts' },
  // Tallon
  { name: PrimeLocation.LANDING_SITE, region: 'Tallon Overworld' },
  { name: PrimeLocation.ALCOVE, region: 'Tallon Overworld' },
  { name: PrimeLocation.FRIGATE_CRASH_SITE, region: 'Tallon Overworld' },
  { name: PrimeLocation.OVERGROWN_CAVERN, region: 'Tallon Overworld' },
  { name: PrimeLocation.ROOT_CAVE, region: 'Tallon Overworld' },
  { name: PrimeLocation.ARTIFACT_TEMPLE, region: 'Tallon Overworld' },
  { name: PrimeLocation.TRANSPORT_TUNNEL_B, region: 'Tallon Overworld' },
  { name: PrimeLocation.ARBOR_CHAMBER, region: 'Tallon Overworld' },
  { name: PrimeLocation.CARGO_FREIGHT_LIFT_TO_DECK_GAMMA, region: 'Tallon Overworld' },
  { name: PrimeLocation.BIOHAZARD_CONTAINMENT, region: 'Tallon Overworld' },
  { name: PrimeLocation.HYDRO_ACCESS_TUNNEL, region: 'Tallon Overworld' },
  { name: PrimeLocation.GREAT_TREE_CHAMBER, region: 'Tallon Overworld' },
  { name: PrimeLocation.LIFE_GROVE_TUNNEL, region: 'Tallon Overworld' },
  { name: PrimeLocation.LIFE_GROVE_START, region: 'Tallon Overworld' },
  { name: PrimeLocation.LIFE_GROVE_UNDERWATER_SPINNER, region: 'Tallon Overworld' },
  // Mines
  { name: PrimeLocation.MAIN_QUARRY, region: 'Phazon Mines' },
  { name: PrimeLocation.SECURITY_ACCESS_A, region: 'Phazon Mines' },
  { name: PrimeLocation.STORAGE_DEPOT_B, region: 'Phazon Mines' },
  { name: PrimeLocation.STORAGE_DEPOT_A, region: 'Phazon Mines' },
  { name: PrimeLocation.ELITE_RESEARCH_PHAZON_ELITE, region: 'Phazon Mines' },
  { name: PrimeLocation.ELITE_RESEARCH_LASER, region: 'Phazon Mines' },
  { name: PrimeLocation.ELITE_CONTROL_ACCESS, region: 'Phazon Mines' },
  { name: PrimeLocation.VENTILATION_SHAFT, region: 'Phazon Mines' },
  { name: PrimeLocation.PHAZON_PROCESSING_CENTER, region: 'Phazon Mines' },
  { name: PrimeLocation.PROCESSING_CENTER_ACCESS, region: 'Phazon Mines' },
  { name: PrimeLocation.ELITE_QUARTERS, region: 'Phazon Mines' },
  { name: PrimeLocation.CENTRAL_DYNAMO, region: 'Phazon Mines' },
  { name: PrimeLocation.METROID_QUARANTINE_B, region: 'Phazon Mines' },
  { name: PrimeLocation.METROID_QUARANTINE_A, region: 'Phazon Mines' },
  { name: PrimeLocation.FUNGAL_HALL_B, region: 'Phazon Mines' },
  { name: PrimeLocation.PHAZON_MINING_TUNNEL, region: 'Phazon Mines' },
  { name: PrimeLocation.FUNGAL_HALL_ACCESS, region: 'Phazon Mines' },
  // Magmoor
  { name: PrimeLocation.LAVA_LAKE, region: 'Magmoor Caverns' },
  { name: PrimeLocation.TRICLOPS_PIT, region: 'Magmoor Caverns' },
  { name: PrimeLocation.STORAGE_CAVERN, region: 'Magmoor Caverns' },
  { name: PrimeLocation.TRANSPORT_TUNNEL_A, region: 'Magmoor Caverns' },
  { name: PrimeLocation.WARRIOR_SHRINE, region: 'Magmoor Caverns' },
  { name: PrimeLocation.SHORE_TUNNEL, region: 'Magmoor Caverns' },
  { name: PrimeLocation.FIERY_SHORES_MORPH_TRACK, region: 'Magmoor Caverns' },
  { name: PrimeLocation.FIERY_SHORES_WARRIOR_SHRINE_TUNNEL, region: 'Magmoor Caverns' },
  { name: PrimeLocation.PLASMA_PROCESSING, region: 'Magmoor Caverns' },
  { name: PrimeLocation.MAGMOOR_WORKSTATION, region: 'Magmoor Caverns' }
];
